### PR TITLE
Fix #250: Added switch in story list filter

### LINKED ISSUE #250: [Feature] Modify the story list filter
## Is your feature request related to a problem? Please describe.

Currently the list of story statuses are displayed on the dashboard itself. 

## Describe the solution you'd like

It would be better if a switch is introduced to toggle between the filter property i.e if all the stories are to be shown or only the stories of a particular status are to be shown. 

The timeline would move inside of the filter and it would be initially hidden. When the user clicks on the toggle to view tickets by timeline, then this appears below and it can be selected, as usual.

## Additional context

A design prototype for the desired feature: https://xd.adobe.com/view/61d5a236-2632-4562-9615-01676a093672-3486/

### PR DESCRIPTION
**Pull request by kailash360**
**Issue Number**

fixes #250 

**Describe the changes you've made**

I have added a new package [`react-switch`](https://www.npmjs.com/package/react-switch) to import the Switch component. I have then added some props to customize the component. I added conditional rendering in the roadmap filter to display it only when the switch is toggled to the **By roadmap status** option. I have also modified the GraphQL query to fetch the stories based on current status.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

https://user-images.githubusercontent.com/75155230/181272567-86a2d0ec-6a65-4dd0-9539-9c17a65c01e7.mp4

### CODE REVIEW

**Comment by mharshita** [comment]
Screenshot 2022-07-31 at 11 48 58 PM
Instead of green switch, use something more appropriate with the color scheme

**Comment by mharshita** [comment]
For the roadmap stage panel, try to make changes accordingly. It should look like a part of the above panel. Make the background white for the roadmap stage, change the border color, and decrease the border width for stages.
Screenshot 2022-07-31 at 11 51 13 PM
Screenshot 2022-07-31 at 11 56 59 PM

**Comment by mharshita** [comment]
Increase space between "All" "Switch" and "By Roadmap Stage". 
If possible, add space between roadmap stages and lines between them (as shown in the design).

**Comment by mharshita** [comment]
Along with the similar changes on the "My Stories" page, can you please revamp these 2 buttons according to something that goes well with the new UI? 
We need to decrease the border width for sure.
Screenshot 2022-08-01 at 12 10 23 AM

**Comment by kailash360** [comment]
@mharshita 
I have pushed the changes

**Review by mharshita — APPROVED** [review]

**Comment by mharshita** [comment]
@kailash360 Can we have the white background behind the timeline just like the proposed UI?

**Comment by kailash360** [comment]
@mharshita 
Done

**Pull request merged**
