### PR TITLE
added notification badge

### LINKED ISSUE #137: Add badge over notification icon
Currently, the notification count just shows the number it would be better to add a badge over it.

### PR DESCRIPTION
**Pull request by codetheorem**
Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Issue Number**

fixes #137 

**Describe the changes you've made**

Added badge over the notification icon in navigation panel.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

1.Go to home page 
2.login into your account
3.see notification icon

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

Home EOS User story

### CODE REVIEW

**Comment by mharshita** [comment]
@codetheorem can we reduce the size of notification badge? Looks quite too large. And can you change the badge color to maybe #F43F5E or #F5222D ?
Screenshot 2022-03-01 at 3 37 14 PM

**Comment by mharshita** [comment]
@codetheorem are all the changes done for this PR? Also, can you resolve the conflicts?

**Comment by codetheorem** [comment]
> @codetheorem are all the changes done for this PR? Also, can you resolve the conflicts?

conflicts resolved

**Comment by mharshita** [comment]
@codetheorem are the changes done for size and color as suggested [here](https://github.com/EOS-uiux-Solutions/user-story/pull/136#issuecomment-1055266896)?
I still cannot see the changes at my end.
Screenshot 2022-03-27 at 5 48 36 PM

**Comment by codetheorem** [comment]
> @codetheorem are the changes done for size and color as suggested [here](https://github.com/EOS-uiux-Solutions/user-story/pull/136#issuecomment-1055266896)? I still cannot see the changes at my end. Screenshot 2022-03-27 at 5 48 36 PM

The custom style was being ignored earlier so I added !important to make the styling visible.

**Pull request closed without merging**
