### PR TITLE
[Bug] Empty toast error

### LINKED ISSUE #201: Error toast notification shows only 'X' icon with no message.
## Describe the bug
When I was creating a new story, I have filled all the fields except the description field. It gives an error by showing a toast notification having only the 'X' icon with no error message. Just like the below image:

## Actual Behavior

Screenshot (994)

## Expected behavior

Screenshot (995)

In the above image, The Toast has the error message along with the icon. It enhances the understandability of the user. 

## To Reproduce

1. Sign in to your account.
2. click on the 'new story' button which is at the top-right corner.
3. Try to fill out the form except for the description field. Then click on the submit button.

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Chrome

### PR DESCRIPTION
**Pull request by kunal00000**
**Issue Number**

fixes #201

**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

**Additional context (OPTIONAL)**
Screenshot 2022-12-31 at 6 56 22 PM

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

Preview: Deploy preview link here with the appropriate route

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by kunal00000** [comment]
what do these tests indicate?
Do I need to change something to pass without fail through the test?

**Comment by kailash360** [comment]
This explains only the error type in the toast box. We also need to show the error message or a one-line explanation of the error.

**Comment by kunal00000** [comment]
Okay working on this but I am not able to figure out that why only on keeping description empty, it gives error response and toast. When all the fields are empty it does not give toast and response error.

**Comment by kunal00000** [comment]
@kailash360 review if this works 

### **If `description` would be empty it would generate error like this.**
Screenshot 2023-01-12 at 2 51 15 AM

### **If any other error persists it would generate like below.**
Screenshot 2023-01-12 at 2 49 57 AM

**I have tried several cases and getting error only when `description` is empty. On submit if `Title Product Category Priority` are empty, form is not submitted until all these are given value.**

**Review by kailash360 — APPROVED** [review]
LGTM

**Comment by kunal00000** [comment]
@kailash360 I have made some changes. 
If description is empty, it will not run try and catch rather directly show error.

**Pull request closed without merging**
