### PR TITLE
Upgraded dependencies

### LINKED ISSUE #114: Update dependencies to latest version
## Is your feature request related to a problem? Please describe.

The application requires NodeJS version to be `13.x.x`  because of the `node-sass 4.13.1` dependency. Considering the upgradation in the NodeJS versions over the recent times, it would be great if we can upgrade the dependencies such that they support the latest versions. This will also allow us to implement new features in the application smoothly.

## Describe the solution you'd like

- All the dependencies should be updated to their latest version, such that they are compatible with the latest stable release of NodeJS.

### PR DESCRIPTION
**Pull request by kailash360**
**Issue Number**

fixes #114 

**Describe the changes you've made**

I have made the following changes:

- Upgraded the dependencies to their latest version
- Fixed breaking changes due to upgraded dependencies
- Fixed the linting errors due to upgraded dependencies
- Updated documentation to install using proper command

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Additional context (OPTIONAL)**

NA

**Test plan (OPTIONAL)**

NA

**Checklist**

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

NA

### CODE REVIEW

**Comment by kailash360** [comment]
@Abhirup-99 

Should I create a different PR for the Cypress tests or add them in this PR itself?

**Comment by Abhirup-99** [comment]
Add the cypress tests in a separate PR. Push 1 more commit to fix the build.

**Comment by kailash360** [comment]
@Abhirup-99 

Some of the Cypress are not meant to work under any condition. This can cause the build to fail. For example, [this](https://github.com/EOS-uiux-Solutions/user-story/blob/main/cypress/integration/user_story.spec.js#L90) line is invalid and hence the test will not pass. 

It can be fixed by replacing the text with appropriate content.

Should I make these minor modifications in the tests as well ?

**Comment by Abhirup-99** [comment]
Yes but the lints would work fine right? Can you push that bit in this PR?

**Comment by kailash360** [comment]
> Yes but the lints would work fine right? Can you push that bit in this PR?

Sure

**Comment by Abhirup-99** [comment]
Tests all go in a separate PR.

**Comment by kailash360** [comment]
@Abhirup-99 

The lint checks have passed

**Comment by Abhirup-99** [comment]
When we are updating the versions, shouldn't it also make sure we don't need to use `-f` flag to install the dependencies. All the dependencies would work fine with `npm install` itself. Can you take care of that in this PR?

**Comment by Abhirup-99** [comment]
2022-01-31-111336_1920x1080_scrot
Build throwing errors.

**Comment by kailash360** [comment]
@Abhirup-99 

The build error appeared because in the latest dependencies, `webpack 5.x.x.` is used, and this caused the import method from JSON file to be erroneous or invalid. 

After changing the import method, the build was successful, and it has also passed the lint checks.

image

**Comment by kailash360** [comment]
@Abhirup-99 

The build error appeared because in the latest dependencies, `webpack 5.x.x.` is used, and this caused the previous import method from JSON file to be erroneous or invalid. 

I have fixed it now. After changing the import method, the build was successful, and it has also passed the lint checks.

image

**Review by Abhirup-99 — APPROVED** [review]

**Pull request merged**
