### PR TITLE
fixed story sorting functionality

### LINKED ISSUE #222: Sorting by most voted or most discussed not working.
## Describe the bug

Sorting stories by most voted or most discussed is not working properly.

## To Reproduce

1. Visit home page
2. Try to sort the stories by most voted or most discussed
3. Use pagination to see other stories that will have more followers or comments.

## Expected behavior

All stories should be able to sort according to the given parameter.

## Environment (please complete the following information):

- OS: Windows
- Browser: Google Chrome

## Additional context

https://userstory.eosdesignsystem.com/story/60ede6e1bdb8130015a83154

### PR DESCRIPTION
**Pull request by codetheorem**
Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Issue Number**

fixes #222 

**Describe the changes you've made**

I have fixed the functionality of sorting in the stories component. I have updated the backend for the same. Currently, the sorting is done only on the frontend hence because of pagination the desired result is not achieved so the sorting must be done on the backend and sent back to the frontend. PR for changes in the backend https://github.com/EOS-uiux-Solutions/strapi/pull/32

**Additional context (OPTIONAL)**

https://userstory.eosdesignsystem.com/story/60ede6e1bdb8130015a83154

**Test plan (OPTIONAL)**

1. Visit the home page.
2. Try to toggle the sorting dropdown

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kailash360** [comment]
@codetheorem 
Please fix the conflicts

**Comment by codetheorem** [comment]
> @codetheorem Please fix the conflicts

@kailash360 done

**Comment by kailash360** [comment]
> > @codetheorem Please fix the conflicts
> 
> @kailash360 done

It would be great if you can make the changes for the tests. It would be a problem in deployment later on.

**Comment by codetheorem** [comment]
> > > @codetheorem Please fix the conflicts
> > 
> > 
> > @kailash360 done
> 
> It would be great if you can make the changes to fix the tests. It would be a problem in deployment later on.

@kailash360 updated !

**Comment by kailash360** [comment]
LGTM 🚀

However, we need to merge the [PR 32](https://github.com/EOS-uiux-Solutions/strapi/pull/32) of EOS User Story strapi to enable the sorting logic.

**Pull request merged**
