### PR TITLE
Okta optional login

### LINKED ISSUE #266: Okta integration: users need the option to either login with Okta or the regular form.
### What

The current implementation of Okta works as follows:
- When the system has SSO enabled, the users are immediately redirected to the Okta login.

The issue with this is that we are not giving people the option to user our regular login.
In other applications there is normally a button "login with Okta" when SSO is enabled, as well as the regular form to login with username + password.

This will be necessary as User Story is meant to be used to gather users' feedback. Any project using User Story would need to offer the option for regular sign-in. The Okta option is valid for internal employees of the organization/project.

### PR DESCRIPTION
**Pull request by codetheorem**
Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Issue Number**

fixes #266 

**Describe the changes you've made**

Added Okta login button on the main authentication page.

**Additional context (OPTIONAL)**

screencapture-localhost-3000-login-1665530234143

**Test plan (OPTIONAL)**

1. Set SSO to true in config.json
2. Then click on the sign-in button on the home page.
3. Check the okta login button

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by cyntss — CHANGES_REQUESTED** [review]
we should improve the fact that the front end is managing the login. Let's remove the need to set up SSO on the config.json, and let's let the backend manage the login providers directly

**Comment by codetheorem** [comment]
Screenshot 2022-10-23 at 8 26 08 PM

One needs to check this permission.

**Comment by cyntss** [comment]
@codetheorem Can you add the documentation about the "check getProvider" on the Strapi UI ?

**Review by cyntss — APPROVED** [review]
LGTM

**Pull request merged**
